import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
    const router = useRouter();
    const [msg, setMsg] = useState<string>("");

    useEffect(() => {
        if (router.asPath.length > 1) {
            router.push(`/verify/${router.asPath}`);
        } else {
            fetch(`/api/gundamget`)
                .then(res => {
                    return res.json();
                })
                .then(res => {
                    setMsg(res.message);
                    console.log(res.message);
                })
                .catch(err => {
                    console.log(err);
                });
        }
    }, [router.asPath]);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main className={styles.main}>{msg ? msg : `loading...`}</main>
        </div>
    );
};

export default Home;
