import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [msg, setMsg] = useState<string>("");
  useEffect(() => {
    fetch(`/api/gundamget`)
      .then((res) => {
        return res.json();
      })
      .then((res) => {
        setMsg(res.message);
        console.log(res.message);
      })
      .catch((err) => {
        console.log(err);
      });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>{msg ? msg : `loading...`}</main>
    </div>
  );
};

export default Home;
