import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
    const router = useRouter();

    useEffect(() => {
        const PARAMS = router.asPath.replace("/verify", "");
        fetch(`/api/grant/${PARAMS}`)
            .then(res => {
                return res.json();
            })
            .then(res => {
                if (res.scope) {
                    router.push("/");
                }
            })
            .catch(err => {
                console.log(err);
            });
    }, [router.asPath]);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main className={styles.main}>Authorizing...</main>
        </div>
    );
};

export default Home;
